const locations = [
    "Mordor",
    "Gondor",
    "Gallifrey",
    "Azeroth",
    "Barsoom",
    "Dune",
    "Camelot",
    "Dinotopia",
    "Hyrule",
    "Lilliput",
    "Middle-earth",
    "Myst",
    "Narnia",
    "Neverland",
    "Oz",
    "Pern",
    "Rowan",
    "Hoth",
    "Alderan",
    "Whoville",
    "Hogwarts",
    "Wonderland",
    "Asgard",
    "Fire Nation",
    "Altea",
    "Crematoria",
    "Fantasia",
    "Pandora",
    "Third Earth",
    "Arrakis",
    "Giedi Prime",
    "Caladan"
]